# Import required pacakges

In [1]:
import numpy as np
import pandas as pd

## Load dataset

In [2]:
# open the txt file in read mode
file = open("data2.txt","r")
# read the file "data2.txt" and split each
# line in the file using newline 
data = file.read().split("\n")

data

['Congrats, You have won!! reply to our sms for a free nokia mobile + free camcorder. \tspam',
 'Congrats! 1 year special cinema pass for 2 is yours. reply to this sms to claim your prize.\tspam',
 'I am pleased to tell you that you are awarded with a 1500 Bonus Prize, reply to this sms to claim your prize.\tspam',
 'Dont worry. I guess he is busy.\tnot spam',
 'Going for dinner. msg you later.\tnot spam',
 'Ok, I will call you up when I get some cash.\tnot spam',
 '']

In [3]:
# futher split each line using tab
data = [d.split("\t") for d in data]

data

[['Congrats, You have won!! reply to our sms for a free nokia mobile + free camcorder. ',
  'spam'],
 ['Congrats! 1 year special cinema pass for 2 is yours. reply to this sms to claim your prize.',
  'spam'],
 ['I am pleased to tell you that you are awarded with a 1500 Bonus Prize, reply to this sms to claim your prize.',
  'spam'],
 ['Dont worry. I guess he is busy.', 'not spam'],
 ['Going for dinner. msg you later.', 'not spam'],
 ['Ok, I will call you up when I get some cash.', 'not spam'],
 ['']]

In [4]:
# remove the last list from the data
del(data[-1])

data

[['Congrats, You have won!! reply to our sms for a free nokia mobile + free camcorder. ',
  'spam'],
 ['Congrats! 1 year special cinema pass for 2 is yours. reply to this sms to claim your prize.',
  'spam'],
 ['I am pleased to tell you that you are awarded with a 1500 Bonus Prize, reply to this sms to claim your prize.',
  'spam'],
 ['Dont worry. I guess he is busy.', 'not spam'],
 ['Going for dinner. msg you later.', 'not spam'],
 ['Ok, I will call you up when I get some cash.', 'not spam']]

## Create a `pandas` dataframe using list

In [5]:
# create a dataframe
data_df = pd.DataFrame(data)
data_df

0         1
0  Congrats, You have won!! reply to our sms for ...      spam
1  Congrats! 1 year special cinema pass for 2 is ...      spam
2  I am pleased to tell you that you are awarded ...      spam
3                    Dont worry. I guess he is busy.  not spam
4                   Going for dinner. msg you later.  not spam
5       Ok, I will call you up when I get some cash.  not spam

In [6]:
# assign name to each column in the dataframe
data_df.columns = ["text","label"]
data_df

text     label
0  Congrats, You have won!! reply to our sms for ...      spam
1  Congrats! 1 year special cinema pass for 2 is ...      spam
2  I am pleased to tell you that you are awarded ...      spam
3                    Dont worry. I guess he is busy.  not spam
4                   Going for dinner. msg you later.  not spam
5       Ok, I will call you up when I get some cash.  not spam

## Data preprocessing

Create a dataset suitable for further computations

In [7]:
vocab = []
text_vector = []

for each in data_df["text"]:
    print(each)
    # collect vocabularies (or words) from input 
    # datafile and store in a list called vocab
    vocab.extend(each.lower().\
                 replace(".","").\
                 replace(",","").\
                 replace("+","").\
                 replace("!","").\
                 replace("1","").\
                 replace("1500","").\
                 replace("2","").\
                 split())
    # collect vocabularies (or words) from input 
    # datafile, however store words in each line 
    # in a list called text_vector
    text_vector.append(each.lower().\
                       replace(".","").\
                       replace(",","").\
                       replace("+","").\
                       replace("!","").\
                       replace("1","").\
                       replace("1500","").\
                       replace("2","").\
                       split())

Congrats, You have won!! reply to our sms for a free nokia mobile + free camcorder. 
Congrats! 1 year special cinema pass for 2 is yours. reply to this sms to claim your prize.
I am pleased to tell you that you are awarded with a 1500 Bonus Prize, reply to this sms to claim your prize.
Dont worry. I guess he is busy.
Going for dinner. msg you later.
Ok, I will call you up when I get some cash.


### Display all words presented in the input file

In [8]:
print(vocab)

['congrats', 'you', 'have', 'won', 'reply', 'to', 'our', 'sms', 'for', 'a', 'free', 'nokia', 'mobile', 'free', 'camcorder', 'congrats', 'year', 'special', 'cinema', 'pass', 'for', 'is', 'yours', 'reply', 'to', 'this', 'sms', 'to', 'claim', 'your', 'prize', 'i', 'am', 'pleased', 'to', 'tell', 'you', 'that', 'you', 'are', 'awarded', 'with', 'a', '500', 'bonus', 'prize', 'reply', 'to', 'this', 'sms', 'to', 'claim', 'your', 'prize', 'dont', 'worry', 'i', 'guess', 'he', 'is', 'busy', 'going', 'for', 'dinner', 'msg', 'you', 'later', 'ok', 'i', 'will', 'call', 'you', 'up', 'when', 'i', 'get', 'some', 'cash']


In [9]:
len(vocab)

78

In [10]:
# remove dublicates words 
vocab = list(set(vocab))
print(vocab)

['prize', 'a', 'call', 'cinema', 'with', 'guess', 'won', 'get', 'awarded', 'to', 'cash', 'nokia', 'pleased', 'am', 'mobile', 'later', 'is', 'he', 'have', 'some', 'ok', 'worry', 'our', 'for', 'msg', 'congrats', 'dinner', 'camcorder', 'your', '500', 'dont', 'claim', 'pass', 'that', 'reply', 'tell', 'year', 'busy', 'sms', 'are', 'special', 'i', 'will', 'free', 'bonus', 'you', 'yours', 'up', 'going', 'when', 'this']


In [11]:
len(vocab)

51

### Display words in each line from the input file

In [12]:
print(text_vector)

[['congrats', 'you', 'have', 'won', 'reply', 'to', 'our', 'sms', 'for', 'a', 'free', 'nokia', 'mobile', 'free', 'camcorder'], ['congrats', 'year', 'special', 'cinema', 'pass', 'for', 'is', 'yours', 'reply', 'to', 'this', 'sms', 'to', 'claim', 'your', 'prize'], ['i', 'am', 'pleased', 'to', 'tell', 'you', 'that', 'you', 'are', 'awarded', 'with', 'a', '500', 'bonus', 'prize', 'reply', 'to', 'this', 'sms', 'to', 'claim', 'your', 'prize'], ['dont', 'worry', 'i', 'guess', 'he', 'is', 'busy'], ['going', 'for', 'dinner', 'msg', 'you', 'later'], ['ok', 'i', 'will', 'call', 'you', 'up', 'when', 'i', 'get', 'some', 'cash']]


### Create a list of list containing number of words presented in each sentence or line 

In [13]:
text_vector_num = []
for text in text_vector:
    vector = []
    # count number of words presented in vocabulary for each line
    for word in vocab:
        vector.append(text.count(word))
    text_vector_num.append(vector)

In [14]:
len(text_vector_num[0])

51

In [15]:
print(text_vector_num[0])

[0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0]


In [16]:
# Display new representation of each sentence in the dataset
for each in text_vector_num:
    print(each)

[0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0]
[1, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1]
[2, 1, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 1]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]
[0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 1, 0]


In [17]:
# insert vocabulary list at index 0
text_vector_num.insert(0, vocab)
print(text_vector_num)

[['prize', 'a', 'call', 'cinema', 'with', 'guess', 'won', 'get', 'awarded', 'to', 'cash', 'nokia', 'pleased', 'am', 'mobile', 'later', 'is', 'he', 'have', 'some', 'ok', 'worry', 'our', 'for', 'msg', 'congrats', 'dinner', 'camcorder', 'your', '500', 'dont', 'claim', 'pass', 'that', 'reply', 'tell', 'year', 'busy', 'sms', 'are', 'special', 'i', 'will', 'free', 'bonus', 'you', 'yours', 'up', 'going', 'when', 'this'], [0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0], [1, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1], [2, 1, 0, 0, 1, 0, 0, 0, 1, 3, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,

### Save data in Excel format

Create a pandas dataframe using numerical text_vector and save the resulting output into an excel file

In [18]:
# create dataframe
counts = pd.DataFrame(text_vector_num)
# save dataframe into an excel file
counts.to_excel("counts.xlsx")
counts

0  1     2       3     4      5    6    7        8   9   ... 41    42  \
0  prize  a  call  cinema  with  guess  won  get  awarded  to  ...  i  will   
1      0  1     0       0     0      0    1    0        0   1  ...  0     0   
2      1  0     0       1     0      0    0    0        0   2  ...  0     0   
3      2  1     0       0     1      0    0    0        1   3  ...  1     0   
4      0  0     0       0     0      1    0    0        0   0  ...  1     0   
5      0  0     0       0     0      0    0    0        0   0  ...  0     0   
6      0  0     1       0     0      0    0    1        0   0  ...  2     1   

     43     44   45     46  47     48    49    50  
0  free  bonus  you  yours  up  going  when  this  
1     2      0    1      0   0      0     0     0  
2     0      0    0      1   0      0     0     1  
3     0      1    2      0   0      0     0     1  
4     0      0    0      0   0      0     0     0  
5     0      0    1      0   0      1     0     0  
6     0      0    1      0   1      0     1     0  

[7 rows x 51 columns]

In [19]:
print(len(text_vector_num[0]))

51


In [20]:
print(len(vocab))

51


### Display `numerical vectors` correspondind to `spam` messages

In [21]:
# get spam message vector
spam = np.array(text_vector_num[1:4])
print('Spam message vectors \n', spam)
print()

Spam message vectors 
 [[0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 1 0
  0 0 1 0 0 0 0 2 0 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 1 0
  1 0 1 0 1 0 0 0 0 0 1 0 0 0 1]
 [2 1 0 0 1 0 0 0 1 3 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1
  0 0 1 1 0 1 0 0 1 2 0 0 0 0 1]]



### Display `numerical vectors` correspondind to `non-spam` messages

In [22]:
# get non-span message vector
ham = np.array(text_vector_num[4:])
print('Ham message vectors \n', ham)

Ham message vectors 
 [[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 2 1 0 0 1 0 1 0 1 0]]


### Compute $𝑝(w_k│spam)$

Probability that a given word ($w_k$ or feature) comes from `spam` messages


#### Number of times a particular word occur in `spam` messages

$n_k$

In [23]:
#### Check the formula in slide 43 (lecture slide)
nk_spam = np.sum(spam,axis=0) 
nk_spam

array([3, 2, 0, 1, 1, 0, 1, 0, 1, 6, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 2, 0, 2, 0, 1, 2, 1, 0, 2, 1, 1, 3, 1, 1, 0, 3, 1, 1, 1, 0, 2,
       1, 3, 1, 0, 0, 0, 2])

#### Number of words in `spam` messages

$n_{spam}$ 

In [24]:
#### Check the formula in slide 43 (lecture slide)
n_spam = np.sum(spam) 
n_spam

54

In [25]:
prob_of_wk_given_spam_message = (nk_spam + 1) / (n_spam + len(vocab))
prob_of_wk_given_spam_message

array([0.03809524, 0.02857143, 0.00952381, 0.01904762, 0.01904762,
       0.00952381, 0.01904762, 0.00952381, 0.01904762, 0.06666667,
       0.00952381, 0.01904762, 0.01904762, 0.01904762, 0.01904762,
       0.00952381, 0.01904762, 0.00952381, 0.01904762, 0.00952381,
       0.00952381, 0.00952381, 0.01904762, 0.02857143, 0.00952381,
       0.02857143, 0.00952381, 0.01904762, 0.02857143, 0.01904762,
       0.00952381, 0.02857143, 0.01904762, 0.01904762, 0.03809524,
       0.01904762, 0.01904762, 0.00952381, 0.03809524, 0.01904762,
       0.01904762, 0.01904762, 0.00952381, 0.02857143, 0.01904762,
       0.03809524, 0.01904762, 0.00952381, 0.00952381, 0.00952381,
       0.02857143])

### Compute $𝑝(w_k│ham)$

Probability that a given word ($w_k$ or feature) comes from **ham** messages


#### Number of times a particular word occur in `ham` messages

$n_k$

In [26]:
nk_ham = np.sum(ham,axis=0) 
nk_ham

array([0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 1, 0,
       0, 2, 0, 1, 1, 1, 0])

#### Number of words in `ham` messages

$n_{ham}$ 

In [27]:
#### Check the formula in slide 43 (lecture slide)
n_ham = np.sum(ham) 
n_ham

24

In [28]:
prob_of_wk_given_ham_message = (nk_ham + 1) / (n_ham + len(vocab))
prob_of_wk_given_ham_message

array([0.01333333, 0.01333333, 0.02666667, 0.01333333, 0.01333333,
       0.02666667, 0.01333333, 0.02666667, 0.01333333, 0.01333333,
       0.02666667, 0.01333333, 0.01333333, 0.01333333, 0.01333333,
       0.02666667, 0.02666667, 0.02666667, 0.01333333, 0.02666667,
       0.02666667, 0.02666667, 0.01333333, 0.02666667, 0.02666667,
       0.01333333, 0.02666667, 0.01333333, 0.01333333, 0.01333333,
       0.02666667, 0.01333333, 0.01333333, 0.01333333, 0.01333333,
       0.01333333, 0.01333333, 0.02666667, 0.01333333, 0.01333333,
       0.01333333, 0.05333333, 0.02666667, 0.01333333, 0.01333333,
       0.04      , 0.01333333, 0.02666667, 0.02666667, 0.02666667,
       0.01333333])

### Compute probabilities of a message being `spam` and `ham`

There are six messages in the file. Out of six messages, 3 are spam and rest of the messages are ham or non-spam.

In [29]:
prob_message_is_spam,prob_message_is_ham = 3/6,3/6
prob_message_is_spam,prob_message_is_ham

(0.5, 0.5)

In [30]:
# Number of words in spam messages
np.sum(spam)

54

In [31]:
# Number of words in the vocabulary
len(vocab)

51

In [32]:
# Number of words in the ham messages
np.sum(ham)

24

### Create new sample messages and process them

In [33]:
new = ["I am busy. I will msg you later.","Congrats! You are awarded a free mobile."]
new_words= []
for each in new:
    processed = each.lower().replace(".","").replace(",","").replace("+","").replace("!","").split()
    new_words.append(processed)
new_words

[['i', 'am', 'busy', 'i', 'will', 'msg', 'you', 'later'],
 ['congrats', 'you', 'are', 'awarded', 'a', 'free', 'mobile']]

### Prediction

In [34]:
def predict(message_list,prob_spam,prob_ham,prob_of_feature_given_spam_message,prob_of_feature_given_ham_message,vocab):
    """
    Returns whether or not the given message (a list of words) is spam or ham
    
    
    Input Parameters
    ---------
    
    message_list: a list of words
    
    prob_spam: a float
    
    prob_ham: a float
    
    prob_of_feature_given_spam_message: an numpy array
    
    prob_of_feature_given_ham_message: an numpy array
    
    vocab: a list of words    
             
    
    """
    spam = prob_spam
    ham = prob_ham
    # compute 𝑝(𝑦) * ∏(𝑗=1 to 𝑑) 𝑝(𝑎_𝑗│𝑦)
    
    for word in message_list:
        spam *= prob_of_feature_given_spam_message[vocab.index(word)]
        ham *= prob_of_feature_given_ham_message[vocab.index(word)]
     
    print('-----------------------------------------')
    print('The given message: ', " ".join(message_list))
    print()
    print('Prob that the given message is spam = ',spam)
    print()
    print('Prob that the given message is ham = ',ham)
    print('------------------------------------------')
    
    
    if spam > ham:
        return " ".join(message_list),"spam"
    else:
        return " ".join(message_list),"ham"

In [35]:
result = predict(new_words[0],prob_message_is_spam,prob_message_is_ham,prob_of_wk_given_spam_message,prob_of_wk_given_ham_message,vocab)
print('Result: ', result[1])


-----------------------------------------
The given message:  i am busy i will msg you later

Prob that the given message is spam =  1.0829429792459005e-15

Prob that the given message is ham =  3.835668952903523e-13
------------------------------------------
Result:  ham


In [36]:
result = predict(new_words[1],prob_message_is_spam,prob_message_is_ham,prob_of_wk_given_spam_message,prob_of_wk_given_ham_message,vocab)
print('Result: ', result[1])

-----------------------------------------
The given message:  congrats you are awarded a free mobile

Prob that the given message is spam =  3.0701433461621255e-12

Prob that the given message is ham =  1.1237311385459537e-13
------------------------------------------
Result:  spam
